POST http://localhost:1337/courses
Content-Type: application/json

{
  "title": "Curso de Git"
}

###

GET http://localhost:1337/courses?orderBy=title

###

GET http://localhost:1337/courses/df48f4f0-c045-4238-889a-c38101113bea
